- conf/distro/include/fsl-base.inc
The preferred version for libdrm is set already in the machine
configuration.
> fsl-base.inc: Remove redundant preferred version for libdrm

- conf/layer.conf
Drop support for sumo and thud releases. If you want to use
theses branches, use the respective platform.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> conf/layer.conf: Support only warrior release

- conf/distro/include/fslc-base.inc
Use Yocto Project Version from Warrior release.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> distro/fslc-base: Change DISTRO_VERSION to 2.7

- conf/distro/include/fslc-base.inc
Use Yocto Project Version from Zeus release.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> distro/fslc-base: Change DISTRO_VERSION to 2.8

- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.0.2.bb
OpenGLES 3.1 is not supported on i.MX 8M Mini, therefore SDK build fails.
This commit splits SDK features to be built based on Machine overrides,
with exclusion of OpenGLES 3.1 for mx8mm. All other machines are explicitly
listed in the recipe with OpenGLES 3.1 support included.
Signed-off-by: Andrey Zhizhikin <andrey.z@gmail.com>
> imx-gpu-sdk: drop OpenGLES 3.1 for i.MX 8M Mini

- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.0.2.bb
This commit serves as a backport of #16 from master to warrior branch.
I was not sure whether someone would perform regular backports, therefore I've performed it on my fork.
--andrey
> warrior: backport #16 from master

- conf/distro/include/fsl-base.inc
- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.0.2.bb
This follows up the [PR #254](https://github.com/Freescale/meta-freescale/pull/254) in _meta-freescale_ layer, which introduces the machine configuration for i.MX8M Nano SoC and corresponding EVK.
> i.mx8m nano machine support in distro layer

- recipes-fsl/packagegroups/packagegroup-fsl-tools-gpu-external.bb
It was removed upstream in commit:
http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-graphics?h=zeus&id=aa36510ebea93c1f6f327152e5aa63beccad0275
Signed-off-by: Mirza Krak <mirza@maneoz.tech>
> packagegroup-fsl-tools-gpu-external: drop eglinfo-x11

- recipes-fsl/packagegroups/packagegroup-fsl-tools-testapps.bb
Update packagegroup RDEPENDS to point python3 packages, python2 has been
dropped from OE-Core since it approached EOL.
Signed-off-by: Andrey Zhizhikin <andrey.zhizhikin@leica-geosystems.com>
> packagegroup-fsl-tools-testapps: update to python3

- recipes-fsl/packagegroups/packagegroup-fsl-tools-gpu.bb
Commit [189229d0f822d62c6e4da19a367f754b0c9162af] in meta-freescale
layer consolidated both libraries and binaries packages for
imx-gpu-apitrace recipe into a singe package.
Drop the reference to -bin package in the package group as it is
reported as missing and would be provided by imx-gpu-apitrace anyway.
Signed-off-by: Andrey Zhizhikin <andrey.zhizhikin@leica-geosystems.com>
> packagegroup-fsl-tools-gpu: remove dropped package reference

- recipes-graphics/glslang/glslang_git.bb
- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.5.3.bb
The vulkan support depends on glslang, so add a new recipe
and a dependency.
> imx-gpu-sdk: Fix build dependency on glslang

- conf/layer.conf
Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
> .conf: Make layer compatible only with dunfell and gatesgarth

- recipes-devtools/stb/stb_git.bb
- recipes-graphics/gli/gli_0.8.2.0.bb
- recipes-graphics/glm/glm_%.bbappend
- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.6.1.bb
Requires https://github.com/Freescale/meta-freescale/pull/532.
> Upgrade imx-gpu-sdk to 5.6.1, aligned with NXP 5.4.47-2.2.0

- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.6.1.bb
The 8M Mini configuration does not include rapidopencl or rapidopenvx,
so remove the incorrect runtime dependencies.
> imx-gpu-sdk: Remove incorrect 8M Mini runtime dependencies

- recipes-graphics/devil/devil_1.8.0.bb
Upstream commit 2456f523cf ("licenses: Update license file to match current SPDX names") deprecated the usage of LGPL-2.1 SPDX identifier, removed LGPL-2.1 license file and replaced it with LGPL-2.1-only SPDX identifier and text file.
Adjust recipe to use new SDPX identifier and text file.
-- andrey
> devil: correct license file to match upstream

- conf/distro/include/fsl-base.inc
The conditional u-boot overrides for the NXP distro are effectively
no-ops since the machine config that they are meant to override takes
precedence. Restore them to unconditional since the intent is to allow
the distro config to override the machine config. This fixes the build
error for imx6qdlsabresd:
```
| install: cannot stat '/opt/work/upstream/fsl-xwayland/tmp/work/imx6qdlsabresd-fsl-linux-gnueabi/u-boot-imx/2020.04-r0/build/u-boot.img': No such file or directory
```
The overrides were made conditional because the SPL_BINARY override is
not correct for i.MX 8M machines. This is because the SPL_BINARY
override is in fact meant for i.MX 6 and 7 only, which is how it was
applied in the original override in meta-freescale before it was moved
to meta-freescale-distro.
Fixes: 880dbf2 …
> fsl-base.inc: Adjust u-boot overrides

- recipes-graphics/gli/gli/0001-Fix-ordered-comparison-of-pointer-and-zero.patch
- recipes-graphics/gli/gli_0.8.2.0.bb
According to the GCC11 Porting Guide [1], error is issued on ordered pointer comparison with integer which causes the following build failure:
```
| test/core/core_convert.cpp:35:85: error: ordered comparison of pointer with integer zero ('const char*' and 'int')
|    35 |         if(std::strstr(FilenameDst, ".dds") > 0 || std::strstr(FilenameDst, ".ktx") > 0)
|       |                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```
Backport upstream patch to correct the ordered comparison.
Link: [1] https://gcc.gnu.org/gcc-11/porting_to.html
> gli: backport upstream patches to resolve gcc11 build

- recipes-fsl/images/fsl-image-multimedia.bb
- recipes-fsl/packagegroups/packagegroup-fsl-tools-testapps.bb
_Clutter_ and _COGL_ recipes were dropped by OE-Core with commit [c4f167d05f5  ("Remove Clutter and Cogl")](http://git.openembedded.org/openembedded-core/commit/?id=c4f167d05f58f35a6b94e8dbc4721ab67e7e71eb).
Remove references to `clutter-1.0-examples` from `RDEPENDS` and `CORE_IMAGE_EXTRA_INSTALL`.
-- andrey
> Remove Clutter examples package

- conf/distro/include/fsl-base.inc
Prevent multiple providers:
```
ERROR: Multiple .bb files are due to be built which each provide linux-mfgtool:
/opt/work/upstream/sources/meta-freescale/recipes-kernel/linux/linux-imx-mfgtool_5.10.bb
/opt/work/upstream/sources/meta-freescale/recipes-kernel/linux/linux-fslc-lts-mfgtool_5.10.bb
```
> fsl-base.inc: Set linux-imx-mfgtool as preferred provider

- recipes-fsl/images/fsl-image-machine-test.bb
1. Firmware loading failure occurs for regulatory.db:
[    3.616070] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    3.624709] platform regulatory.0: Falling back to sysfs fallback for: regulatory.db
[   64.473750] cfg80211: failed to load regulatory.db
2. Firmware loading failure occurs for imx-sdma if set to builtin:
[   64.474069] imx-sdma 20ec000.sdma: Direct firmware load for imx/sdma/sdma-imx6q.bin failed with error -2
[   64.496589] imx-sdma 20ec000.sdma: Falling back to sysfs fallback for: imx/sdma/sdma-imx6q.bin</div>
[  125.913831] imx-sdma 20ec000.sdma: external firmware not found, using ROM firmware
Add firmwared to the image to provide firmware loading for the
firmware fallback mechanism.
Signed-off-by: Tom Hochstein …
> fsl-image-machine-test: Add firmwared

- recipes-fsl/packagegroups/packagegroup-fsl-tools-gpu.bb
This is a follow-up for https://github.com/Freescale/meta-freescale/pull/844, which excludes the currently broken `imx-gpu-apitrace` package from package group until it is updated to be compatible with newer glibc.
-- andrey
> packagegroup-fsl-tools-gpu: exclude broken imx-gpu-apitrace

- recipes-fsl/packagegroups/packagegroup-fsl-tools-gpu.bb
imx-gpu-apitrace package has additional patch and can be build with `glibc >= 2.34`
This reverts commit 92c75c69e2edd834f9a5c3f47115805e45e28608.
This PR is linked with https://github.com/Freescale/meta-freescale/pull/857
Cc: @thochstein
> Revert "packagegroup-fsl-tools-gpu: exclude broken imx-gpu-apitrace"

- conf/distro/fsl-wayland.conf
- conf/distro/fsl-xwayland.conf
- conf/distro/fslc-wayland.conf
- conf/distro/fslc-xwayland.conf
Since OE-Core commit 8d0b4704a5 ("defaultsetup.conf: enable select init manager"), init manager setting is moved to a separate variable and simplified.
[Yocto documentation](https://docs.yoctoproject.org/singleindex.html#init-system-selection) suggests that the new syntax should be used to define init manager in distro definitions.
Convert all syntax to use new init system selection.
> conf: distro: use proper syntax to define init system

- recipes-fsl/images/fsl-image-multimedia.bb
This will cause the SYSTEMD_DEFAULT_TARGET to be set to graphical.target (rootfs-postcommands.bbclass), which is needed otherwise weston does not start on boot.
> fsl-image-multimedia: conditionally add weston to IMAGE_FEATURES

- recipes-fsl/images/fsl-image-multimedia.bb
If wayland is in DISTRO_FEATURES weston is installed in
CORE_IMAGE_EXTRA_INSTALL so include it in IMAGE_FEATURES as well.
> Backport to hardknott - fsl-image-multimedia: conditionally add weston to IMAGE_FEATURES

- conf/distro/include/fslc-base.inc
- recipes-graphics/wayland/weston-init.bbappend
- recipes-graphics/wayland/weston-init/profile
The variable is not set for ssh or console, causing app failures. It's
not clear if this is an error or by design, but setting it manually
does help and doesn't seem to hurt.
See https://github.com/Freescale/meta-freescale/pull/858
> weston-init: Set XDG_RUNTIME_DIR manually

- recipes-graphics/vulkan/assimp/0001-assimp-remove-shared-lib-from-_IMPORT_CHECK_TARGETS.patch
- recipes-graphics/vulkan/assimp/0001-closes-https-github.com-assimp-assimp-issues-2733-up.patch
- recipes-graphics/vulkan/assimp/use-GNUInstallDirs-where-possible.patch
- recipes-graphics/vulkan/assimp_5.0.1.bb
The recipe assimp was dropped from OE-core due to license issues and the
lack of any dependency.
The recipe is needed by imx-gpu-sdk, so copy it locally, with an extra
patch to remove the license issues.
Fixes #71 
> assimp: Add recipe

- recipes-graphics/vulkan/assimp_5.0.1.bb
The patch to remove non-compliant source fails due to the existence of
binaries.
Drop the patch and instead remove the non-compliant source manually
from do_unpack.
Fixes #72
> assimp: Replace failing patch

- recipes-devtools/stb/stb_git.bb
- recipes-graphics/glslang/glslang_git.bb
Recent Bitbake update introduced following commits in attempt to adapt to [new requirement from GitHub](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git):
```
86a9c268 ("fetch2/git: Add a warning asking users to set a branch in git urls")
42526a40 ("fetch/git: Show warning for invalid github urls")
```
There is a warning issued for those recipes that either do not explicitly provide branch parameter to the Bitbake fetcher, or still
using unauthenticated git:// protocol.
Adapt recipes across layer to accommodate for those new requirements.
-- andrey
> layer: set missing branch and protocol for recipes using git

- recipes-graphics/gli/gli_0.8.4.0.bb
- recipes-graphics/rapidopencl/rapidopencl_1.1.0.1.bb
- recipes-graphics/rapidopenvx/rapidopenvx_1.1.0.bb
- recipes-graphics/rapidvulkan/rapidvulkan_1.2.162.0.bb
- recipes-graphics/vulkan/assimp_5.0.1.bb
This fixes warnings from Bitbake, which were introduced to adhere to [GitHub requirements](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git)
> recipes-graphics: correct fetch links using github

- conf/distro/include/fslc-base.inc
The user cannot disable buildhistory from local.conf because it is set
in fslc-base.inc. Use a default setting instead.
> fslc-base.inc: Allow override of BUILDHISTORY_COMMIT

- conf/layer.conf
It's not backward ABI compatible with honister due to variable renaming.
> layer.conf: Bump to kirkstone

- recipes-fsl/fsl-rc-local/fsl-rc-local.bb
- recipes-graphics/devil/devil_1.8.0.bb
- recipes-multimedia/gstreamer/gst-variable-rtsp-server_1.0.bb
Since OE-Core commit [`9379f80f48 ("license/insane: Show warning forobsolete license usage")`](https://github.com/openembedded/openembedded-core/commit/9379f80f484f94686a4d494e9e237fadfb72a938), `LICENSE` field not containing SPDX identifiers are treated with _WARNING_.
An automated conversion using OE-Core `scripts/contrib/convert-spdx-licenses.py` to convert to use the standard SPDX license identifiers has been done on the entire layer.
> Update LICENSE variable to use SPDX license identifiers

- conf/distro/include/fslc-base.inc
Since commit dcf889e93401f7c4de0055d53271eacc3882eccc in OE: [
meta: Remove remnants of bluez4 support
bluez4 was removed from meta-oe 2 years ago.
Simplfy the setup of the two level bluetooth and bluez4/bluez5
distro features by removing the bluez4/bluez5 distro features.
This also removes the no longer required bluetooth class.
Signed-off-by: Adrian Bunk <bunk@stusta.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
]
bluez5 is no longer a distro feature, and there is no reference to it neither in Freescale/OE meta layers, let's drop it.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
> distro:fslc-base.inc: drop bluez5 from DISTRO_FEATURES

- conf/distro/include/fslc-base.inc
While there aren't many recipe setting the instruction set to arm anymore, the way the fslc distro sets thumb as the default is still wrong.
> fslc-base: fix setting of used instruction set

- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk-src.inc
- recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_6.1.1.bb
Release 6.1.1
- GCC13 support.
- Small wayland bug fix.
- Vulkan.NativeWindowTest update.
- New 'feature' to make it easier to filter apps during testing.
- Scr version updated.
> imx-gpu-sdk: Upgrade 6.1.0 -> 6.1.1

- recipes-graphics/wayland/weston-init.bbappend
- recipes-graphics/wayland/weston-init/profile
The profile script setting WAYLAND_DISPLAY is now handled in OE-Core and can be dropped.
https://github.com/openembedded/openembedded-core/commit/1600f38d72818cda78a4731354dbecc144f664c9
Note that our profile script was in fact correct only for the systemd case, since it's only there that Yocto sets the Wayland socket to the non-default value `/run/wayland-0`.
> weston-init: Drop profile script now handled by OE-Core

- recipes-multimedia/gstreamer/gst-variable-rtsp-server_1.0.bb
Github has announced there will be no more git:// fetching from their servers: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
> recipes: Update github.com urls to use https

- recipes-connectivity/openssh/openssh_%.bbappend
The bbappend is added to disable rng-tools originally as [1], but the rng-tools has been already removed in oe-core as [2]. So no need to keep this bbappend which used to disable rng-tools. And the means used to disable rng-tools [1] also make the sshd service not work after the logic [3] introduced.
So remove the useless bbappend.
[1] https://github.com/Freescale/meta-freescale-distro/commit/131b33554d8617b8c02fe932eb4624a1d7b701a7
[2] https://git.openembedded.org/openembedded-core/commit/?id=868dfb46d96a27ec9041cb902fb769330277257d
[3] https://git.openembedded.org/openembedded-core/commit/?id=bc830ad3c6a11af1a350dca7f33f0682aeee0d21
> openssh: Remove the bbappend

- recipes-fsl/packagegroups/packagegroup-fsl-tools-testapps.bb
fsl-rc-local is for sysvinit, so include it only when sysvinit is in DISTRO_FEATURES.
> packagegroup-fsl-tools-testapps: Drop fsl-rc-local if no sysvinit

- conf/distro/include/fslc-base.inc
Update distro version to be based on scarthgap release
> fslc-base: Update distro version to be based on scarthgap release

- conf/distro/include/fsl-base.inc
Update gstreamer version to aligin with scarthgap-6.6.52_2.2.0
1.24.0 -> 1.24.7
> fsl-base.inc: Update gstreamer1.0-plugin-base/bad/good version to 1.24.7

- conf/layer.conf
Fix current error:
ERROR: Layer freescale-distro is not compatible with the core layer which only supports these series: whinlatter (layer is compatible with styhead walnascar)
> layer.conf: update for the whinlatter release series

- conf/layer.conf
- recipes-devtools/half/half_2.1.0.bb
- recipes-fsl/fsl-rc-local/fsl-rc-local.bb
This is a not backward compatible change. Not all layers did the update as of now.
This change is needed if one updates oe-core to commit cedc4ff7c9bc ("meta: remove consecutive blank lines") or later, however not all layer will then behave as expected.
> updates for WORKDIR/UNPACKDIR and git fetch location 
